#!/bin/bash
# Swap the module set between the patched stack and a clean v2_17_55, so the
# same suites can run against both in one boot.  The build is ~95 s, so a real
# baseline is affordable; what costs time is the suites themselves.
#
#   bash 11-swap.sh patched | baseline
set -e
MODE="${1:?usage: 11-swap.sh patched|baseline}"
KVER=$(uname -r)
cd ~/lustre-release

# Tear the filesystem all the way down first.  `make install` replaces
# /sbin/mount.lustre, and if anything Lustre is still mounted the install dies
# with "Device or resource busy" -- leaving the PREVIOUS modules in place while
# the script reports a new build.  That failure mode silently turns a
# patched-vs-baseline comparison into patched-vs-patched.
cd lustre/tests && bash llmountcleanup.sh > /tmp/cleanup.log 2>&1 || true
cd ~/lustre-release
umount -a -t lustre 2>/dev/null || true
sleep 2
lustre_rmmod 2>/dev/null || true
zpool export -a 2>/dev/null || true
if mount | grep -q lustre; then
	echo "still mounted after cleanup:"; mount | grep lustre; exit 1
fi

# reset --hard already restores every TRACKED file, which is all the patches
# touch.  Do not `git clean` here: lustre/include/lustre_ver.h is generated by
# configure and untracked, so cleaning that directory deletes it and the build
# dies before it starts.
git checkout -q .
git reset -q --hard v2_17_55
# (lustre_ver.h lives at include/uapi/linux/lustre/ and is generated by the
# build, not by configure -- nothing to restore here.)
if [ "$MODE" = patched ]; then
	for p in rec-attr rec-attr-zfs parallel-it itable-readahead \
	         itable-blockparse otable-xattr; do
		git apply ~/lfu/patches/$p-v2_17_55.patch || { echo "apply $p failed"; exit 1; }
	done
	echo "applied the six-patch stack"
else
	echo "clean v2_17_55"
fi

make -j"$(nproc)" > /tmp/make-$MODE.log 2>&1 || {
	echo "BUILD FAILED"; grep -nE 'error:' /tmp/make-$MODE.log | head -20; exit 1; }
make install > /tmp/install-$MODE.log 2>&1 || {
	echo "INSTALL FAILED"; grep -E "cannot|Error" /tmp/install-$MODE.log | head -5; exit 1; }
depmod -a

# Verify the INSTALLED module, not the one in the build tree.  The build tree
# is always right; what matters is what insmod will pick up.
INST=$(find /lib/modules/"$KVER" -name osd_zfs.ko | head -1)
echo "$MODE: installed $INST"
if nm "$INST" | grep -qw osd_otable_it_xattr; then have=patched; else have=baseline; fi
echo "  installed module looks: $have"
[ "$have" = "$MODE" ] || { echo "  MISMATCH: asked for $MODE, installed $have"; exit 1; }
